DROP TABLE DR_DREAM;
DROP TABLE DR_DREAM_LIST;
DROP TABLE DR_USER_INFO;

CREATE TABLE DR_DREAM (
       DREAM_LIST_ID INTEGER,
       TITLE VARCHAR(255) NOT NULL,
       BODY VARCHAR(2048) NOT NULL,
       IP_ADDRESS CIDR,
       UPDATE_DATE TIMESTAMP DEFAULT "timestamp"('now'::text) NOT NULL,
       CREATE_DATE TIMESTAMP DEFAULT "timestamp"('now'::text) NOT NULL,
       PRIMARY KEY (DREAM_LIST_ID)
);

CREATE TABLE DR_DREAM_LIST (
       DREAM_LIST_ID SERIAL,
       USER_ID INTEGER NOT NULL,
       UPDATE_DATE TIMESTAMP DEFAULT "timestamp"('now'::text) NOT NULL,
       CREATE_DATE TIMESTAMP DEFAULT "timestamp"('now'::text) NOT NULL,
       PRIMARY KEY (USER_ID)
);

CREATE TABLE DR_USER_INFO (
       ID SERIAL,
       USER_NAME VARCHAR(16) NOT NULL UNIQUE,
       USER_IMAGE VARCHAR(1024),
       ACCESS_TOKEN VARCHAR(1024) NOT NULL,
       UPDATE_DATE TIMESTAMP DEFAULT "timestamp"('now'::text) NOT NULL,
       CREATE_DATE TIMESTAMP DEFAULT "timestamp"('now'::text) NOT NULL,
       PRIMARY KEY(ID)
);

CREATE INDEX USER_ID_INDEX ON DR_DREAM_LIST(USER_ID);
