DROP TABLE DR_DREAM;
DROP TABLE DR_USER;

CREATE TABLE DR_DREAM (
       ID SERIAL,
       TITLE VARCHAR(255) NOT NULL,
       BODY VARCHAR(2048) NOT NULL,
       CATEGORY VARCHAR(255) NOT NULL,
       USER_ID INTEGER NOT NULL,
       UPDATE_DATE TIMESTAMP DEFAULT "timestamp"('now'::text) NOT NULL,
       CREATE_DATE TIMESTAMP DEFAULT "timestamp"('now'::text) NOT NULL,
       PRIMARY KEY (ID)
);

CREATE TABLE DR_USER (
       ID SERIAL,
       USER_NAME VARCHAR(16) NOT NULL UNIQUE,
       USER_IMAGE VARCHAR(1024),
       UPDATE_DATE TIMESTAMP DEFAULT "timestamp"('now'::text) NOT NULL,
       CREATE_DATE TIMESTAMP DEFAULT "timestamp"('now'::text) NOT NULL,
       PRIMARY KEY(ID)
);

